version: "3"

services:
  tibiadata:
    image: ghcr.io/tibiadata/tibiadata-api-go:${TIBIADATA_IMAGE_LABEL}
    restart: always
    environment:
      - TIBIADATA_HOSTNAME=${TIBIADATA_HOSTNAME}
      - TIBIADATA_EDITION=${TIBIADATA_EDITION}
      - GIN_TRUSTED_PROXIES=${GIN_TRUSTED_PROXIES}
      - DEBUG_MODE=false
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    ports:
      - 8080:8080
