version: "3.9"

services:
  # TibiaData API
  tibiadata-api:
    image: ghcr.io/tibiadata/tibiadata-api-go:${TIBIADATA_IMAGE_LABEL:-latest}
    restart: always
    environment:
      # Required environment variables
      - TIBIADATA_HOST=${TIBIADATA_HOST:?TIBIADATA_HOST is required}

      # Optional environment variables
      - TIBIADATA_PROXY=${TIBIADATA_PROXY:-}
      - TIBIADATA_PROXY_PROTOCOL=${TIBIADATA_PROXY_PROTOCOL:-}
      - GIN_TRUSTED_PROXIES=${GIN_TRUSTED_PROXIES:-}

      # Default environment variables
      - GIN_MODE=${GIN_MODE:-release}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - TIBIADATA_EDITION=${TIBIADATA_EDITION:-open-source}
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    ports:
      - 8080:8080
