version: "3.9"

x-kong-config: &kong-env
  KONG_DATABASE: postgres
  KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
  KONG_PG_HOST: kong-db
  KONG_PG_USER: ${KONG_PG_USER:-kong}
  KONG_PG_PASSWORD: ${KONG_PG_PASSWORD:-abc123}

services:
  # Postgres: Kong Database
  kong-db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD: ${KONG_PG_PASSWORD:-abc123}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${KONG_PG_DATABASE:-kong}",
          "-U",
          "${KONG_PG_USER:-kong}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - kong_data:/var/lib/postgresql/data

  # Kong: database migration
  kong-migrations:
    image: "${KONG_DOCKER_TAG:-kong/kong:latest-ubuntu}"
    command: kong migrations bootstrap
    depends_on:
      kong-db:
        condition: service_healthy
    environment:
      <<: *kong-env
    restart: on-failure

  # Kong: database migration-up
  kong-migrations-up:
    image: "${KONG_DOCKER_TAG:-kong/kong:latest-ubuntu}"
    command: kong migrations up && kong migrations finish
    depends_on:
      kong-db:
        condition: service_healthy
    environment:
      <<: *kong-env
    restart: on-failure

  # Kong: The API Gateway
  kong:
    image: "${KONG_DOCKER_TAG:-kong/kong:latest-ubuntu}"
    container_name: kong-api
    depends_on:
      kong-db:
        condition: service_healthy
    environment:
      <<: *kong-env
      KONG_LOG_LEVEL: warn
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001 reuseport, 0.0.0.0:8444 http2 ssl reuseport"
      KONG_PROXY_ACCESS_LOG: /dev/null
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PROXY_LISTEN: "0.0.0.0:8000 reuseport, 0.0.0.0:8443 http2 ssl reuseport"
      KONG_PREFIX: ${KONG_PREFIX:-/var/run/kong}
    ports:
      - ${KONG_PORT_PROXY_HTTP:-8000}:8000
      - 8001:8001
      - ${KONG_PORT_PROXY_HTTPS:-8443}:8443
      - 8444:8444
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure:5
    volumes:
      - kong_prefix_vol:${KONG_PREFIX:-/var/run/kong}
      - kong_tmp_vol:/tmp
    security_opt:
      - no-new-privileges

volumes:
  kong_data: {}
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
